global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'collector'
    static_configs:
      - targets: [ 'collector:9201' ]

  - job_name: 'mq_metrics'
    static_configs:
      - targets: [ 'mq:9157' ]