---
# Source: producer/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: producer
  labels:
    helm.sh/chart: producer-0.1.0
    app.kubernetes.io/name: producer
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: producer/templates/cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: producer
  labels:
    helm.sh/chart: producer-0.1.0
    app.kubernetes.io/name: producer
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "Kafka": {
        "ProducerSettings": {
          "BootstrapServers": "broker.jared.svc.cluster.local:29092"
        },
        "TopicName": "poc_topic"
      },
      "AllowedHosts": "*",
      "OTEL_EXPORTER_OTLP_ENDPOINT": "http://collector.jared.svc.cluster.local::4317"
    }
---
# Source: producer/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: producer
  labels:
    helm.sh/chart: producer-0.1.0
    app.kubernetes.io/name: producer
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: producer
    app.kubernetes.io/instance: test
---
# Source: producer/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    helm.sh/chart: producer-0.1.0
    app.kubernetes.io/name: producer
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: producer
      app.kubernetes.io/instance: test
  template:
    metadata:
      labels:
        helm.sh/chart: producer-0.1.0
        app.kubernetes.io/name: producer
        app.kubernetes.io/instance: test
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: producer
      securityContext:
        {}
      containers:
        - name: producer
          securityContext:
            {}
          image: "ghcr.io/jaredmichaelhawkins/dotnet-kafka-images-producer:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
          volumeMounts:
            - mountPath: /app/config
              name: config-volume
              subPath: appsettings.json
      volumes:
        - configMap:
            items:
            - key: appsettings.json
              path: appsettings.json
            name: producer
          name: config-volume
