name: Consumer Build and Push

on:
    workflow_dispatch:

jobs:
    build_and_push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Consumer/Dockerfile
                  push: true
                  tags: ghcr.io/jaredmichaelhawkins/${{ github.event.repository.name }}-consumer:latest
